### ISSUE TITLE
I try and add a webhook using the gui, but get an error response for CRC, need help

### ISSUE THREAD

**Issue by Mikeac94** [twitterdev/account-activity-dashboard#20]
I get this error => Non-200 response code during CRC GET request (i.e. 404, 500, etc). I want to know how can i get the crc token and then register my webhook

**Comment by Mikeac94** [comment]
@jcipriano

**Comment by mkgareja** [comment]
getting same error

any update @Mikeac94

**Comment by andypiper** [comment]
Hello. Have you listed your callback URL on the developer dashboard? where are you seeing this error?

**Comment by aran-arunakiri** [comment]
same issue

**Comment by andypiper** [comment]
Where are you seeing the error, and what are you seeing in the console for the dashboard application?

**Comment by gauloics** [comment]
At first I also experienced it if I did in IDE default browser, then it works when I open it using the device's browser.
But unfortunately this does not work to add subscriptions, always fails on GUI. But still working with scripts.

this is the error code

> Error: Callback URL not approved for this client application. Approved callback URLs can be adjusted in your application settings
    at Strategy.parseErrorResponse (/home/runner/account-activity-dashboard/node_modules/passport-twitter/lib/strategy.js:206:12)
    at Strategy.OAuthStrategy._createOAuthError (/home/runner/account-activity-dashboard/node_modules/passport-oauth1/lib/strategy.js:405:16)
    at /home/runner/account-activity-dashboard/node_modules/passport-oauth1/lib/strategy.js:252:41
    at /home/runner/account-activity-dashboard/node_modules/oauth/lib/oauth.js:543:17
    at passBackControl (/home/runner/account-activity-dashboard/node_modules/oauth/lib/oauth.js:397:13)
    at IncomingMessage.<anonymous> (/home/runner/account-activity-dashboard/node_modules/oauth/lib/oauth.js:409:9)
    at IncomingMessage.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

**Comment by gauloics** [comment]
> At first I also experienced it if I did in IDE default browser, then it works when I open it using the device's browser.
> But unfortunately this does not work to add subscriptions, always fails on GUI. But still working with scripts.
> 
> this is the error code
> 
> > Error: Callback URL not approved for this client application. Approved callback URLs can be adjusted in your application settings
> > at Strategy.parseErrorResponse (/home/runner/account-activity-dashboard/node_modules/passport-twitter/lib/strategy.js:206:12)
> > at Strategy.OAuthStrategy._createOAuthError (/home/runner/account-activity-dashboard/node_modules/passport-oauth1/lib/strategy.js:405:16)
> > at /home/runner/account-activity-dashboard/node_modules/passport-oauth1/lib/strategy.js:252:41
> > at /home/runner/account-activity-dashboard/node_modules/oauth/lib/oauth.js:543:17
> > at passBackControl (/home/runner/account-activity-dashboard/node_modules/oauth/lib/oauth.js:397:13)
> > at IncomingMessage. (/home/runner/account-activity-dashboard/node_modules/oauth/lib/oauth.js:409:9)
> > at IncomingMessage.emit (events.js:326:22)
> > at endReadableNT (_stream_readable.js:1241:12)
> > at processTicksAndRejections (internal/process/task_queues.js:84:21)

all URLs are registered on the twitter dev portal correctly, because it works if run with a script, only the GUI is the problem

**Comment by gauloics** [comment]
> At first I also experienced it if I did in IDE default browser, then it works when I open it using the device's browser.
> But unfortunately this does not work to add subscriptions, always fails on GUI. But still working with scripts.
> 
> this is the error code
> 
> > Error: Callback URL not approved for this client application. Approved callback URLs can be adjusted in your application settings
> > at Strategy.parseErrorResponse (/home/runner/account-activity-dashboard/node_modules/passport-twitter/lib/strategy.js:206:12)
> > at Strategy.OAuthStrategy._createOAuthError (/home/runner/account-activity-dashboard/node_modules/passport-oauth1/lib/strategy.js:405:16)
> > at /home/runner/account-activity-dashboard/node_modules/passport-oauth1/lib/strategy.js:252:41
> > at /home/runner/account-activity-dashboard/node_modules/oauth/lib/oauth.js:543:17
> > at passBackControl (/home/runner/account-activity-dashboard/node_modules/oauth/lib/oauth.js:397:13)
> > at IncomingMessage. (/home/runner/account-activity-dashboard/node_modules/oauth/lib/oauth.js:409:9)
> > at IncomingMessage.emit (events.js:326:22)
> > at endReadableNT (_stream_readable.js:1241:12)
> > at processTicksAndRejections (internal/process/task_queues.js:84:21)

this happened after 
`npm audit fix`
because after installation there is a warning
![Screenshot_2021-08-28-23-13-55-82](https://user-images.githubusercontent.com/742131/131226674-b65baf0a-1d43-456b-9a55-d97158bcda2c.jpg)
